name: Update Portfolio History

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portfolio History Update
        run: |
          curl -X POST "${{ secrets.NEXT_PUBLIC_APP_URL }}/api/cron/update-history" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"